# Generated by Django 3.2.4 on 2021-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='s_class',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
