# Generated by Django 3.2.4 on 2021-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_students_s_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'student_class',
            },
        ),
    ]
