# Generated by Django 3.2.4 on 2021-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_class', models.CharField(blank=True, max_length=50, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_classnew',
                'managed': False,
            },
        ),
    ]
