# Generated by Django 3.2.4 on 2021-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentclassnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='present',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
