# Generated by Django 3.2.4 on 2021-06-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studentclass_present'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclassnew',
            options={},
        ),
    ]
