# Generated by Django 3.2.4 on 2021-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_studentclassnew_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassnew',
            name='present2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
