# Generated by Django 3.2.4 on 2021-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210617_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassnew',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnew',
            name='present',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
