# Generated by Django 3.2.4 on 2021-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210617_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassnew',
            name='present3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
