# Generated by Django 3.2.4 on 2021-06-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_studentclassnew_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclassnew',
            options={},
        ),
    ]
